services:
  ebr-postgres:
    image: postgres:18.3-bookworm
    container_name: ebr-env-postgres
    env_file:
      - .env
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: always

  # golang-migrate
  ebr-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: ebr-env-mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro # read-only
    restart: unless-stopped

    